---
title: "PSYR6003_Assignment_1_Cameron"
author: "Cameron"
format: html
editor: visual
---

```{r}
#INSTALL AND LIBRARY


#install.packages("tidyverse")
#install.packages("haven")
#install.packages("pwr)
#install.packages("TOSTER")
#install.packages("metafor")

library(tidyverse)
library(haven)
library(pwr)
library(TOSTER)
library(metafor)
```

```{r}
#**********READING IN AND CLEANING DATASET**************
Avengers_dataset <- read_csv("avengers.csv") #read in the dataset (make sure                                                      tidyverse is libraried in)
#**********INSPECTING THE DATA*************
names(Avengers_dataset) #lists the columns of the dataset
glimpse(Avengers_dataset) #shows what type of data the columns are
anyNA(Avengers_dataset) #are there missing values in the dataset?

Avengers_dataset %>%
  summarise(#summarise the dataset into a one row table
    across(everything(),#do this next function across every column
           ~ sum(is.na(.x)))) #?across help page. count how many missing values are                                in the column I am looking at (.x), which is applied                                to all columns because of the previous function

#**********CLEANING DATASET************
AD_clean <- drop_na(Avengers_dataset)#?drop_na help page. drops rows                                                      containing any missing values
anyNA(AD_clean)#confirming it contains no missing values (= false,                                  so no missing values)
nrow(Avengers_dataset)#checking how many rows the original dataset had
nrow(AD_clean)#checking how many rows the clean set has (i.e.,how many were dropped)
  

```

```{r}
#****creating Combat Effectiveness variable********
AD_clean_CE <- mutate(AD_clean, CombatEffectiveness = (agility+speed+strength+willpower))# ?mutate help page. MUTATE MODIFIES OR ADDS C O L U M N S. function(name of dataset, name of new column to add, or name of column to edit = (what its made of))
names(AD_clean_CE)#confirming new column was added
anyNA(AD_clean_CE)#confirming no missing values in this new dataset
```

```{r}
#************Create a new copy of the dataset in both SPSS and csv formats that only includes the avengers who did not have a superpower and have died********
AD_clean_CE %>% count(superpower, died)#checking how many had superpowers and died

#?filter.FILTER REMOVES R O W S
AD_clean_CE_nosup_died <- AD_clean_CE %>%
  filter(superpower == "no", died == "yes") #creating new dataset for no super power +died. Take the AD_clean_CE dataset and apply(pipe) it to the filter function, which removes rows that dont contain the correct responses for superpower and died. i.e., keep only the rows that match my conditions.
#use == instead of =. one equals means your assigning something. two equals is checking if something is equal to a certain value

write_csv(AD_clean_CE_nosup_died, "AD_Clean_CE_nosup_died.csv")
write_sav(AD_clean_CE_nosup_died, "AD_Clean_CE_nosup_died.sav")
```

```{r}
#**********Overall Summary of AD_Clean_CE data************
Summary_stats_overall <- AD_clean_CE_nosup_died %>% #create object using dataset
  summarise(n = n(),
            Average_CE = mean(CombatEffectiveness, na.rm = TRUE), 
            sd_CE = sd(CombatEffectiveness, na.rm = TRUE),
            min_CE = min(CombatEffectiveness, na.rm = TRUE),
            max_CE = max(CombatEffectiveness, na.rm = TRUE), #summarize mean,sd, and min/max range
            
            Average_kills = mean(kills, na.rm = TRUE),
            sd_kills = sd(kills, na.rm = TRUE),
            min_kills = min(kills, na.rm = TRUE),
            max_kills = max(kills, na.rm = TRUE),
            
            Average_injuries = mean(injuries, na.rm = TRUE),
            sd_injuries = sd(injuries, na.rm = TRUE),
            min_injuries = min(injuries, na.rm = TRUE),
            max_injuries = max(injuries, na.rm = TRUE))
Summary_stats_overall #show the table
```

```{r}
#**********Location split Summary of AD_Clean_CE data************
Summary_stats_location <- AD_clean_CE_nosup_died %>%
  group_by(north_south) %>%
  summarise(n = n(),
            Average_CE = mean(CombatEffectiveness, na.rm = TRUE),
            sd_CE = sd(CombatEffectiveness, na.rm = TRUE),
            min_CE = min(CombatEffectiveness, na.rm = TRUE),
            max_CE = max(CombatEffectiveness, na.rm = TRUE),
            
            Average_kills = mean(kills, na.rm = TRUE),
            sd_kills = sd(kills, na.rm = TRUE),
            min_kills = min(kills, na.rm = TRUE),
            max_kills = max(kills, na.rm = TRUE),
            
            Average_injuries = mean(injuries, na.rm = TRUE),
            sd_injuries = sd(injuries, na.rm = TRUE),
            min_injuries = min(injuries, na.rm = TRUE),
            max_injuries = max(injuries, na.rm = TRUE))
Summary_stats_location
```

```{r}
AD_clean_CE %>% #investigating iq summary stats for effect size justification. (not necessary, but I wanted the practice)
  summarise(n = n(),
            mean_iq = mean(iq, na.rm = TRUE),
            sd_iq = sd(iq, na.rm = TRUE))
```

```{r}
#*********POWER ANALYSIS********
pwr.t.test(d = .5,
           power = .9,
           sig.level = 0.05,
           type = "two.sample",
           alternative = "two.sided")

#*******TOST*******
power_t_TOST(low_eqbound = -0.2,
             high_eqbound = 0.2,
             alpha = .05,
             power = .9,
             type = "two.sample")



```

```{r}
#*******cleaning final dataset for question 10*********
Avengers_dataset %>% count(superpower) #seeing an issue with the original dataset. One of the superpower responses is "yes" instead of yes. the "yes", has iq, and we can therefore include it in the iq/superpower analysis. so we must clean it BEFORE actual analysis.

Avengers_dataset_clean_superpower <- Avengers_dataset %>%
  mutate(
    superpower = gsub('"', '', superpower))# getting rid of the additional "" in the yes variable. first argument is the pattern we want to fix ('"' (notice that ' is surrounding ")), and second argument is what we want to replace it with('' (we are replacing it with nothing)). ?gsub help page. dont need it for this specific case, but other functions that could be helpful for future projects: "tolower(superpower)" (converts everything to lowercase), OR "trimws(superpower)" (removes extra spaces at beginning or end of name/string)

Avengers_dataset_clean_superpower %>% count(superpower)#confirming the new dataset is clean/doesnt contain "yes" anymore.

Avengers_dataset_clean_superpower_iq <- Avengers_dataset_clean_superpower %>%
  filter(!is.na(iq), !is.na(superpower)) # removing NA values from the variables of interest. filter removes rows based on conditions. "is.na(iq)" Checks whether the IQ value is missing. the "!" essentially means "not", so "!is.na(iq)" means that the function is checking if the value is NOT missing. so, this function is basically keeping all of the rows that match my conditions (not missing for iq and suopor power), and eliminating/filtering any others.

Avengers_dataset_clean_superpower_iq %>% count(superpower)#confirming final clean dataset contains only cases that have yes/no answer, without missing values



#**********effect size and CI calculation******USING THE ACTUAL GROUP SIZES FROM OUR DATASET Avengers_dataset_clean_superpower_iq

Independent_stats <- escalc(measure = "SMD",
                            ti = 4.25,
                            n1i = 780,
                            n2i = 33,
                            var.names = c("g","variance"))
summary(Independent_stats)


#determining qualitative labels for each effect size range
cohen.ES(test = "t", size = "small") #The label you put in quotes is what you can change to see the corresponding effect.
cohen.ES(test = "t", size = "medium") #The label you put in quotes is what you can change to see the corresponding effect.
cohen.ES(test = "t", size = "large") #The label you put in quotes is what you can change to see the corresponding effect.

#g of 0.7546 is just shy of a "large" effect (0.8). 
```
